const data = [
  {
    id: 1,
    header: "AI Ethics Policy Review",
    type: "Research",
    status: "Pending",
    target: "Q4 2025",
    limit: "2 Weeks",
    reviewer: "Dr. Mensah",
  },
  {
    id: 2,
    header: "NOMA Simulation Refinement",
    type: "Technical",
    status: "Approved",
    target: "Q3 2025",
    limit: "1 Month",
    reviewer: "Prof. Adeyemi",
  },
  {
    id: 3,
    header: "5G Network Slice Optimization",
    type: "Experiment",
    status: "In Review",
    target: "Q2 2025",
    limit: "3 Weeks",
    reviewer: "Dr. Osei",
  },
  {
    id: 4,
    header: "Blockchain Audit for IoT Logs",
    type: "Audit",
    status: "Rejected",
    target: "Q1 2025",
    limit: "10 Days",
    reviewer: "Eng. Owusu",
  },
  {
    id: 5,
    header: "Data Integrity Verification",
    type: "Research",
    status: "Approved",
    target: "Q2 2025",
    limit: "1 Week",
    reviewer: "Dr. Agyeman",
  },
  {
    id: 6,
    header: "Quantum Communication Model",
    type: "Proposal",
    status: "Pending",
    target: "Q4 2025",
    limit: "2 Months",
    reviewer: "Dr. Boadu",
  },
  {
    id: 7,
    header: "Edge Node Synchronization",
    type: "Technical",
    status: "In Progress",
    target: "Q1 2026",
    limit: "3 Weeks",
    reviewer: "Prof. Amankwah",
  },
  {
    id: 8,
    header: "Deepfake Detection Framework",
    type: "Security",
    status: "In Review",
    target: "Q3 2025",
    limit: "1 Month",
    reviewer: "Dr. Opoku",
  },
  {
    id: 9,
    header: "ISAC Beamforming Metrics",
    type: "Research",
    status: "Completed",
    target: "Q2 2025",
    limit: "5 Days",
    reviewer: "Dr. Nartey",
  },
  {
    id: 10,
    header: "Federated Learning Node Update",
    type: "AI System",
    status: "Pending",
    target: "Q1 2026",
    limit: "2 Weeks",
    reviewer: "Prof. Quartey",
  },
];

export default data;
